### ISSUE TITLE
unable to sync shadow service of service name bigger then 63 char

### ISSUE THREAD

**Issue by korenlev** [traefik/mesh#817] opened 2022-03-01 23:39 UTC
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

invalid: metadata.name: Invalid value: \"traefik-pushprox-kube-controller-manager-proxy-6d61657368-monitoring\": must be no more than 63 characters" 

### What did you see instead?

no workaround

### What version of Traefik are you using?

2.5

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

k8s

**Comment by kevinpollet** [comment] 2022-03-03 09:00
Hello @korenlev and thanks for your interest in Traefik mesh,

The issue you are facing is a duplicate of #746 which has been addressed by #772. As this is a breaking change the fix is only available on master. In the meantime, you may want to use the [`ignoreNamespaces`](https://github.com/traefik/mesh-helm-chart/blob/master/mesh/README.md#configuration) or [`watchNamespaces`](https://github.com/traefik/mesh-helm-chart/blob/master/mesh/README.md#configuration) configuration options to exclude namespaces containing services which should not be meshed.

According to this, we will close this issue as a duplicate.

**Closed by kevinpollet** 2022-03-03 09:00 UTC
Labels: contributor/waiting-for-feedback, status/0-needs-triage
